### ISSUE TITLE
`ChessBoardRobot` does not perform `drag()` inputs correctly

### ISSUE THREAD

**Issue by matt989253** [epfl-SDP/android#193] opened 2022-03-30 11:19 UTC
The `ChessBoardRobot` does not perform `drag()` inputs correctly.

It appears to drag the `Piece` to where it was asked to, but somehow does not release it. This results in illegal moves that appear to be performed, such as having two pieces on the same square.

Here is a test that should pass with the correct behavior, but does not:
```
fun illegalMoveByDragging_isNotPossible() = runTest {
    val robot = emptyGameAgainstOneselfRobot()

    robot.performInput { drag(ChessBoardState.Position(4, 0), ChessBoardState.Position(7, 7)) }

    // White Rook is still here
    robot.assertHasPiece(7, 7, White, Rook)
    // Black King did not move
    robot.assertHasPiece(4, 0, Black, King)
}
```

**Comment by alexandrepiveteau** [comment] 2022-03-30 11:33
I think `drag()` releases the pieces correctly, especially since the same pointer is used to perform additional gestures afterwards.

However, the issue might come from the timing of the animation, which makes it look like the piece move was successful when it's just that the piece is not done animating back to its starting position.

**Comment by alexandrepiveteau** [comment] 2022-05-31 18:26
Marking this as _wontfix_ since I think it is the intended behaviour. The Play DSL on `ChessBoardRobot` uses `click` under-the-hood and there's therefore no risk that it ends in inconsistent states.

**Closed by alexandrepiveteau** 2022-05-31 18:26 UTC
Labels: bug
